FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-buster as build
 
RUN install_packages build-essential git-core make imagemagick libv4l-dev libjpeg-dev cmake git  curl

RUN curl -fsSL https://code-server.dev/install.sh | sh

FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:10-buster

COPY --from=build /usr/local /usr/local

EXPOSE 8080

RUN mkdir /config

CMD code-server

