FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-node:14-bullseye

# Update and install necessary packages
RUN apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y

# Install Python3, distutils, and other dependencies
RUN apt-get install -y build-essential git python3 wget i2c-tools python3-distutils python3-dev libpython3-dev libc-dev

# Install pip
RUN wget https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py

# Install Adafruit_GPIO and spidev
RUN pip3 install Adafruit_GPIO spidev

# Install CNCjs
RUN npm install cncjs@latest

EXPOSE 8000

RUN mkdir /config
RUN install_packages i2c-tools




# Install required Python libraries for OLED
RUN pip3 install Adafruit_SSD1306 Pillow RPi.GPIO websocket-client requests

# Copy the custom .cncrc configuration file
COPY .cncrc /config/.cncrc

# Add the Python script to display IP on OLED
COPY display_ip.py /usr/src/app/
#RUN python3 /usr/src/app/display_ip.py &
CMD /node_modules/cncjs/bin/cncjs -H 0.0.0.0 -p 8000  --config /config/.cncrc
